### ISSUE TITLE
A4.3

### ISSUE THREAD

**Issue by alebarled** [gii-is-psg2/PSG2-2021-G3-35#104]

**Comment by alebarled** [comment]
Buenas, en este Sprint vamos a revisar cada una de las épicas. Pido a la persona encargada de esta revisión que cualquier duda o problema que pueda surgir lo comente formalmente por aquí. Muchas gracias.

**Comment by aleruijur** [comment]
Lo primero que puedo ver es que el punto de introducción está vacío. Rellenarlo explicando que se va a el documento en cuestión a rasgos generales.

**Comment by aleruijur** [comment]
Tampoco se os puede olvidar incluir una mejora en la plantilla del documento que nos remarcaron en la corrección del entregable anterior. Si no recuerdo mal, nos recomendaban incluir una tabla de versionado y un pie de página.
